name: CI

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        emacs: ['emacs-24.1-travis', 'emacs-25.1-travis', 'emacs-26.2-travis']
    name: Emacs ${{ matrix.emacs }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup Emacs
        uses: emacs-php/github-actions-evm@master
        with:
          version: ${{ matrix.emacs }}
      - run: emacs --version
